services:
  comfyui-base:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8188:8188"
    volumes:
      - ./comfyui-input:/comfyui/input
      - ./comfyui-output:/comfyui/output
      - ./comfyui-models:/comfyui/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all

  redis:
    image: redis:8.2.0
    container_name: td-redis
    ports:
      - 6379:6379
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services
    environment:
      - SERVICES=s3

volumes:
  redis_data: